//This is the shopping cart data

let shopItemsData = [
  {
    id: "casualshirt",
    name: "Casual Shirt",
    price: 45,
    desc: "A casual shirt for everyday wear.",
    img: "./images/img-1.jpg",
  },
  {
    id: "officeshirt",
    name: "Office Shirt",
    price: 100,
    desc: "A light office shirt for long days in the office.",
    img: "./images/img-2.jpg",
  },
  {
    id: "tshirt",
    name: "T-Shirt",
    price: 25,
    desc: "A sturdy and soft T-Shirt for all occations.",
    img: "./images/img-3.jpg",
  },
  {
    id: "suit",
    name: "Mens Suit",
    price: 300,
    desc: "A beautiful 3-piece suit for fancy and casual days.",
    img: "./images/img-4.jpg",
  },
  {
    id: "tie",
    name: "Mens Tie",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-5.png",
  },
  {
    id: "casualshoes",
    name: "Casual shoes",
    price: 200,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-6.png",
  },
  {
    id: "blacksuit",
    name: "black suit",
    price: 450,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-7.png",
  },
  {
    id: "poloshirt",
    name: "polo shirt",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-8.png",
  },
  {
    id: "denimshirt",
    name: "denim shirt",
    price: 85,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-9.png",
  },
  {
    id: "denimpant",
    name: "denim pants",
    price: 120,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-10.png",
  },
  {
    id: "basiccap",
    name: "basic cap",
    price: 35,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-11.png",
  },
  {
    id: "leatherboots",
    name: "leather boots",
    price: 350,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/img-12.png",
  },
];
